import type { Metadata } from "next";
import '@fontsource/inter/latin.css';
import "./globals.css";
import background from "../images/blue_bg.png"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={"latin-font"}>{children}</body>
  </html>
  );
}
